apiVersion: v1
kind: Service
metadata:
  name: task-controller
  labels:
    app: task-controller
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: task-controller
