apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-controller
  labels:
    app: task-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-controller
  template:
    metadata:
      labels:
        app: task-controller
    spec:
      containers:
        - name: task-controller
          image: task-controller
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
