apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  type: ClusterIP
  clusterIP: 10.96.185.105
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
